name: Generate terraform docs
on:
  - pull_request

jobs:
  terraform-docs-generator:
    name: Generate terraform docs
    uses: truefoundry/github-workflows-public/.github/workflows/terraform-doc-generator.yml@v0.1.1
    with:
      commit_ref: ${{ github.event.pull_request.head.ref }}
